name: deploy

on:
  push:
    branches: [ main ]
    paths: [ 'dict/**', 'game/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest

    steps:
    # Git repo set up
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Make
    - name: Make build
      working-directory: ${{github.workspace}}
      run: make

    # Deploy on GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: ${{github.workspace}}/build/
